# Generated by Django 5.1.3 on 2024-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('irrenunciable', models.BooleanField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
