# Generated by Django 5.1.3 on 2024-11-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feriado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feriado',
        ),
    ]
